apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freeradius.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "freeradius.name" . }}
    helm.sh/chart: {{ include "freeradius.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  clients.conf: |
    client k8s-ikev2 {
        ipaddr = 	10.8.0.0/8
        secret = testing123
    }
  authorize: |
    bob    Cleartext-Password := "testing123"