apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freeradius.name" . }}
    helm.sh/chart: {{ include "freeradius.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 1812
      targetPort: 1812
      protocol: UDP
      name: server
    - port: 1813
      targetPort: 1813
      protocol: UDP
      name: server-bind
  selector:
    app.kubernetes.io/name: {{ include "freeradius.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
