apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strongswan.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strongswan.name" . }}
    helm.sh/chart: {{ include "strongswan.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "strongswan.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "strongswan.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: ike
              containerPort: 500
              protocol: UDP
            - name: ike-nat
              containerPort: 4500
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
          volumeMounts:
            - name: config-ipsec
              mountPath: /etc/ipsec.conf
              subPath: ipsec.conf
            - name: config-ipsecrets
              mountPath: /etc/ipsec.secrets
              subPath: ipsec.secrets
            - name: config-radius
              mountPath: /etc/strongswan.d/charon/eap-radius.conf
              subPath: eap-radius.conf
            - mountPath: /etc/ipsec.d/cacerts/chain.pem
              name: cert-chain
              subPath: chain.pem
            - mountPath: /etc/ipsec.d/certs/cert.pem
              name: cert-fullchain
              subPath: cert.pem
            - mountPath: /etc/ipsec.d/private/privkey.pem
              name: cert-private
              subPath: privkey.pem
      hostNetwork: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config-ipsec
          configMap:
            defaultMode: 420
            items:
              - key: ipsec.conf
                path: ipsec.conf
            name: {{ .Release.Name }}-{{ .Chart.Name }}-config
        - name: config-ipsecrets
          configMap:
            defaultMode: 420
            items:
              - key: ipsec.secrets
                path: ipsec.secrets
            name: {{ .Release.Name }}-{{ .Chart.Name }}-config
        - name: config-radius
          configMap:
            defaultMode: 420
            items:
              - key: eap-radius.conf
                path: eap-radius.conf
            name: {{ .Release.Name }}-{{ .Chart.Name }}-config
        - name: cert-chain
          secret:
            defaultMode: 493
            items:
            - key: chain.pem
              path: chain.pem
            optional: false
            secretName: {{ .Release.Name }}-{{ .Chart.Name }}-cert
        - name: cert-fullchain
          secret:
            defaultMode: 493
            items:
            - key: cert.pem
              path: cert.pem
            optional: false
            secretName: {{ .Release.Name }}-{{ .Chart.Name }}-cert
        - name: cert-private
          secret:
            defaultMode: 493
            items:
            - key: privkey.pem
              path: privkey.pem
            optional: false
            secretName: {{ .Release.Name }}-{{ .Chart.Name }}-cert