apiVersion: v1
kind: Service
metadata:
  name: {{ include "strongswan.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "strongswan.name" . }}
    helm.sh/chart: {{ include "strongswan.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 500
      targetPort: 500
      protocol: UDP
      name: ike
    - port: 4500
      targetPort: 4500
      protocol: UDP
      name: ike-nat
  selector:
    app.kubernetes.io/name: {{ include "strongswan.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}