# Default values for freeradius.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: freeradius/freeradius-server
  tag: 3.0.19-alpine
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
   cpu: 100m
   memory: 512Mi
  requests:
   cpu: 10m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
