# Default values for strongswan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: newops/strongswan
  tag: 5.7.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 10m
   memory: 16Mi

# privilegedVpnPod: Run the strongSwan VPN pod with privileged authority.  Normally this is not required.
# An error message logged by the VPN pod will indicate when privileged authority is required.
#   true  = Run the VPN pod with privileged authority
#   false = Run the VPN pod with NET_ADMIN authority
privilegedVpnPod: false

nodeSelector: {}

tolerations: []

affinity: {}
